# Path C nrUE — SAT_LEO_TRANS + IMSI for CN5G.
# LEO attach (pathc-bringup-du0): UE = RFsim CLIENT, DU0 = server.
# Dual-DU HO (pathc-du1-ho): UE = RFsim SERVER — requires weak nr_update_sib19
# in librfsimulator (see oai-config/patches/apply-rfsim-sib19-stub.sh).
# SPDX-License-Identifier: LicenseRef-CSSL-1.0

uicc0 = {
  imsi = "001010000000001";
  key = "fec86ba6eb707ed08905757b1bb44b8f";
  opc= "C42449363BBAD02B66D16BC975D77CC1";
  pdu_sessions = ({ dnn = "oai"; nssai_sst = 1; });
};

position0 = {
    x = 0.0;
    y = 0.0;
    z = 6377900.0;
};

rfsimulator = (
  {
    serveraddr = "127.0.0.1";
    serverport = 4043;
    prop_delay = 20;
    options = ("chanmod");
  }
);

channelmod = {
  max_chan = 10;
  modellist = "modellist_rfsimu_1";
  modellist_rfsimu_1 = (
    {
      model_name     = "rfsimu_channel_enB0";
      type           = "SAT_LEO_TRANS";
      noise_power_dB = -100;
    },
    {
      model_name     = "rfsimu_channel_ue0";
      type           = "SAT_LEO_TRANS";
      noise_power_dB = -100;
    }
  );
};
